# -*- coding: utf-8 -*-
"""Datacleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FQiuCKVuLoLvVsbR1GZ_Qs6OBXm8COX
"""

import pandas as pd

# Load the dataset
file_path = 'Financials.csv'  # Make sure the file is in the same folder as this script
df = pd.read_csv(file_path)

# Display initial data info
print("Initial Dataset Info:")
print(df.info())
print("\nMissing values per column:\n", df.isnull().sum())
print("\nFirst few rows of data:\n", df.head())

# Step 1: Drop duplicates
df.drop_duplicates(inplace=True)

# Step 2: Drop columns with all missing values
df.dropna(axis=1, how='all', inplace=True)

# Step 3: Fill missing values
# Fill numeric columns with the mean
# Fill numeric columns with the mean
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Fill object (text) columns with 'Unknown'
text_cols = df.select_dtypes(include=['object']).columns
df[text_cols] = df[text_cols].fillna('Unknown')

df.to_csv('Financials_cleaned.csv', index=False)
print("Cleaned dataset saved as: Financials_cleaned.csv")

from google.colab import files
files.download('Financials_cleaned.csv')